name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Start local web server
      run: |
        python3 server.py > server.log 2>&1 &
        sleep 15

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: 'http://127.0.0.1:8080'
        rules_file_name: ''
        fail_on_error: 'false'
        format: 'html,json'
        output_file: 'zap-reports/report.html'

    - name: Fail if High/Critical alerts exist
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y jq
        REPORT=zap-reports/report.json
        if [ ! -f "$REPORT" ]; then
          echo "::error::ZAP report not found at $REPORT"
          exit 1
        fi
        HIGH_COUNT=$(jq '[.site[].alerts[]? | select(.risk=="High" or .risk=="Critical")] | length' $REPORT)
        echo "High/Critical alerts: $HIGH_COUNT"
        if [ "$HIGH_COUNT" -gt 0 ]; then
          echo "::error::ZAP found $HIGH_COUNT High/Critical alerts. Failing the job."
          jq '.site[].alerts[]? | select(.risk=="High" or .risk=="Critical") | {name, risk, uri, param, evidence, cweid}' $REPORT
          exit 1
        fi
        echo "No High/Critical alerts found."

    - name: Upload ZAP HTML report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-reports/report.html

    - name: Upload ZAP JSON report
      uses: actions/upload-artifact@v4
      with:
        name: zap-json-report
        path: zap-reports/report.json
